apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: kiali-operator
spec:
  auth:
    strategy: anonymous

  deployment:
    accessible_namespaces:
      - "**"

  external_services:
    prometheus:
      url: http://monitoring-kube-prometheus-prometheus.monitoring:9090

    grafana:
      enabled: true
      in_cluster_url: http://monitoring-grafana.monitoring:80

    tracing:
      enabled: true
      provider: tempo
