apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend
  namespace: opssphere

spec:
  replicas: 2

  selector:
    matchLabels:
      app: backend

  strategy:
    type: RollingUpdate

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend

          image: chandanbharadwaj007/opssphere-backend:v2
          imagePullPolicy: Always

          ports:
            - containerPort: 3000

          envFrom:
            - configMapRef:
                name: opssphere-config

          readinessProbe:
            httpGet:
              path: /health
              port: 3000

            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /health
              port: 3000

            initialDelaySeconds: 30
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"