apiVersion: v1
kind: Service

metadata:
  name: mongodb

spec:
  selector:
    app: mongodb

  ports:
    - port: {{ .Values.mongodb.service.port }}
      targetPort: {{ .Values.mongodb.service.port }}

  type: ClusterIP