{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: opssphere-istio
  namespace: {{ .Release.Namespace }}
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}

  selector:
    matchExpressions:
      - key: security.istio.io/tlsMode
        operator: Exists

  podMetricsEndpoints:
    - targetPort: 15090
      path: /stats/prometheus
      interval: 15s
{{- end }}