apiVersion: batch/v1
kind: Job

metadata:
  name: opssphere-seed
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation

spec:
  backoffLimit: 3

  template:
    spec:
      restartPolicy: Never

      containers:
        - name: seed

          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}

          envFrom:
            - configMapRef:
                name: opssphere-config

          command:
            - npm
            - run
            - seed